from services.FuncionarioService import FuncionarioService
from services.ProvinciaService import ProvinciaService
from services.DistritoService import DistritoService
from services.DepartamentoService import DepartamentoService
from services.PresencaFuncionarioService import PresencaFuncionarioService
from services.DashboardService import DashboardService
from services.TreinamentoService import TreinamentoService
